#!/bin/bash

# get bootstrap and react dependencies
wget http://fb.me/react-0.9.0.min.js -P /opt/lambda-shelf/resources/public/react/react-0.9.0.min.js
wget https://github.com/twbs/bootstrap/releases/download/v3.1.1/bootstrap-3.1.1-dist.zip -P /opt/lambda-shelf/resources/public/bootstrap/
wget http://code.jquery.com/jquery-1.11.0.min.js -P /opt/lambda-shelf/resources/public/bootstrap/

# unpack and remove archives
cd /opt/lambda-shelf/resources/public/bootstrap/; unzip bootstrap-*.zip; mv bootstrap-3*/* ./; rm -rf bootstrap-3*; rm -f bootstrap-*.zip
